services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    networks:
      - app-network

  bank-service:
    build:
      context: .
    volumes:
      - ./configs:/app/configs
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data:
  prometheus-data:
  grafana-data:
