package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.68

import (
	"bank-service/graph"
	"bank-service/graph/model"
	"bank-service/internal/entity"
	"context"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, id int32, balance int32) (*model.User, error) {
	user := &entity.CreateAccount{UserID: int(id), Balance: int(balance)}
	res, err := r.DB.CreateAccount(user)
	if err != nil {
		return nil, err
	}
	return &model.User{ID: int32(res.ID), Balance: int32(res.Balance.Sum)}, nil
}

// GetBalance is the resolver for the getBalance field.
func (r *queryResolver) GetBalance(ctx context.Context, id int32) (*model.User, error) {
	user := &entity.GetBalance{UserID: int(id)}
	res, err := r.DB.GetBalance(user)
	if err != nil {
		return nil, err
	}
	return &model.User{ID: int32(res.ID), Balance: int32(res.Balance.Sum)}, nil
}

// Mutation returns MutationResolver implementation.
//func (r *graph.Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
//func (r *graph.Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *graph.Resolver }
type queryResolver struct{ *graph.Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
*/
