// Code generated by MockGen. DO NOT EDIT.
// Source: d:\\go\bank-service\internal\rabbit\rabbit.go

// Package mock_rabbit is a generated GoMock package.
package mock_rabbit

import (
	entity "bank-service/internal/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRabbitI is a mock of RabbitI interface.
type MockRabbitI struct {
	ctrl     *gomock.Controller
	recorder *MockRabbitIMockRecorder
}

// MockRabbitIMockRecorder is the mock recorder for MockRabbitI.
type MockRabbitIMockRecorder struct {
	mock *MockRabbitI
}

// NewMockRabbitI creates a new mock instance.
func NewMockRabbitI(ctrl *gomock.Controller) *MockRabbitI {
	mock := &MockRabbitI{ctrl: ctrl}
	mock.recorder = &MockRabbitIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRabbitI) EXPECT() *MockRabbitIMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRabbitI) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRabbitIMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRabbitI)(nil).Close))
}

// NewConnection mocks base method.
func (m *MockRabbitI) NewConnection() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewConnection")
	ret0, _ := ret[0].(error)
	return ret0
}

// NewConnection indicates an expected call of NewConnection.
func (mr *MockRabbitIMockRecorder) NewConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewConnection", reflect.TypeOf((*MockRabbitI)(nil).NewConnection))
}

// SendToPaymentService mocks base method.
func (m *MockRabbitI) SendToPaymentService(user *entity.UpdateBalance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendToPaymentService", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendToPaymentService indicates an expected call of SendToPaymentService.
func (mr *MockRabbitIMockRecorder) SendToPaymentService(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendToPaymentService", reflect.TypeOf((*MockRabbitI)(nil).SendToPaymentService), user)
}
