// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID      int32 `json:"id"`
	Balance int32 `json:"balance"`
}
