app:
  port: 8080
  appVersion: "1.0.0"
database:
  host: "postgres-container"
  port: 5432
  dbname: "postgres"
  user: "my_user"
  password: 1234
  maxconnections: 20
rabbitmq:
  nameOfQueue: "queueOfPayment"
  rabbitUrl: "amqp://guest:guest@rabbitmq:5672/"


  